---
- hosts: redhat
  become: yes
  remote_user: sysadmin

  roles:
  - webserver

  tasks:

  - name: Create virtualhost configuration directory
    file:
      path: /etc/httpd/vhosts.d
      state: directory
      owner: root

  - name: Copy virtualhost configuration
    copy:
      src: ./files/virtualhost.conf
      dest: /etc/httpd/vhosts.d/ejemplo.conf
    notify: Restart apache

  - name: Include vhosts directory
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional /etc/httpd/vhosts.d/*.conf  
  

  - name: Copy index file
    template:
      src: ./files/index.j2
      dest: /var/www/ejemplo/html/index.html
      owner: apache
      group: apache
      mode: '644'

  handlers:

  - name: Restart apache
    service:
      name: httpd
      state: restarted
